name: 'PR build'

on:
  pull_request:
    branches:
      - 'master'
      - 'release/**'

env:
  WEBPACK_MODE: prd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn run getdeps
      - run: yarn run prerelease
